version: "2"
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    links:
      - db
    restart: always
      # Permite sincronizar la carpeta de trabajo durante el desarrollo
      # de la aplicación
  db:
    image: mongo
    expose: 
      - "27017"
    restart: always
    volumes: 
      - mongodata:/data/db
volumes:
  mongodata: